apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  annotations:
    scenarios.ai.sap.com/name: "MLOps public pipeline"
    scenarios.ai.sap.com/description: "Introduction to docker pipeline"
    executables.ai.sap.com/name: "monitor-scoring-code"
    executables.ai.sap.com/description: "Executable description for scoring code"
  labels:
    ai.sap.com/version: "7.0"
    scenarios.ai.sap.com/id: "test-scenario-id-123"
  name: monitor-scoring-code-1

spec:
  inputs:
    parameters:
      - name: MLOPS_DEPLOYMENT_ID
        type: string
      - name: MLOPS_MODEL_ID
        type: string
      - name: MLOPS_IMAGE_NAME
        type: string
        default: docker.io/dulcardo/scoring-code:02
      - name: MLOPS_SECRETS_NAME
        type: string
        default: datarobot-secrets
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      labels: |
        ai.sap.com/resourcePlan: "starter"
    spec: |
      predictor:
        minReplicas: 1
        containers:
        - name: kserve-container
          image: "{{inputs.parameters.MLOPS_IMAGE_NAME}}"
          imagePullPolicy: Always
          ports:
           - containerPort: 9001
             protocol: TCP
          env:
            - name: MLOPS_DEPLOYMENT_ID
              value: "{{inputs.parameters.MLOPS_DEPLOYMENT_ID}}"
            - name: MLOPS_MODEL_ID
              value: "{{inputs.parameters.MLOPS_MODEL_ID}}"
            - name: DATAROBOT_ENDPOINT
              valueFrom:
                secretKeyRef:
                    name: "{{inputs.parameters.MLOPS_SECRETS_NAME}}"
                    key: DATAROBOT_ENDPOINT
            - name: DATAROBOT_API_TOKEN
              valueFrom:
                secretKeyRef:
                    name: "{{inputs.parameters.MLOPS_SECRETS_NAME}}"
                    key: DATAROBOT_API_TOKEN
        timeout: 30
